# ?????? ?? ??
server:
  port: 80

# MariaDB ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1111

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

# ??? ???? ???? ??? ???? ??
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# ?? ??? ??? ??
itemImgLocation: /Users/seonghun/Desktop/shop/item

# ??? ??? ??
uploadPath: file:///Users/seonghun/Desktop/shop/
